### ISSUE TITLE
dotnet 8.0.1 support

### ISSUE THREAD

**Issue by matbest1** [highbyte/sonarscan-dotnet#29]
Hello, would be good to have support for dotnet 8.0.1

Actually my action fail:
![dotnet 8 0 1](https://github.com/highbyte/sonarscan-dotnet/assets/5552456/4b1ead40-a88e-4332-a19f-b167a80ae397)

**Comment by highbyte** [comment]
v2.3.1 is now released with your changes. Thanks!
