### ISSUE TITLE
Coverage won't be analyzed ?

### ISSUE THREAD

**Issue by SVYSHE** [highbyte/sonarscan-dotnet#9]
So hello again, 

I'm that guy again :D 

Subjecting my Repository [Jobb](https://github.com/SVYSHE/Jobb) again. 
So as I can see the fetch depth is set to 0

`steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'`

Wouldn't that mean, that the tests inside JobbTest should be analyzed too and there should be a coverage on the [sonarcloud project](https://sonarcloud.io/dashboard?id=SVYSHE_Jobb)?

**Comment by highbyte** [comment]
Setting fetch-depth to 0 disables git shallow clone, which will enable some functionality in SonarQube/SonarCloud. It's optional, see here:
https://github.com/highbyte/sonarscan-dotnet#sonarqubesonarcloud-dashboard-warning-shallow-clone-detected-during-the-analysis

It shouldn't effect code coverage. To collect code coverage in a format that SonarQube/SonarCloud understands, see example by using Coverlet here
https://github.com/highbyte/sonarscan-dotnet#include-code-coverage-with-coverlet

**Comment by SVYSHE** [comment]
As you can see in my [SonarScan Pipeline](https://github.com/SVYSHE/Jobb/blob/master/.github/workflows/build.yml) i added the exact lines but still no coverage to see in the [SonarCloud project](https://sonarcloud.io/dashboard?id=SVYSHE_Jobb&branch=master).. any ideas ?

In the output you can clearly see that the pipeline is indeed testing..

![pipeline-output](https://user-images.githubusercontent.com/58707844/101378914-f5425a80-38b3-11eb-9af3-527f144e1fef.png)

**Comment by highbyte** [comment]
No problem!
